FROM node:20-slim

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable

WORKDIR /home/node

COPY . .

RUN yarn install --frozen-lockfile
ENV NODE_ENV=development

EXPOSE 13120

RUN yarn global add nodemon

CMD ["yarn", "dev"]